//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwnData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class AppUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUser()
        {
            this.Purchases = new HashSet<Purchase>();
            this.Households = new HashSet<Household>();
            this.MadeWishes = new HashSet<Wish>();
            this.GrantedWishes = new HashSet<Wish>();
        }
    
        [Key]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Email required")]
        [EmailAddress(ErrorMessage = "Email must be in correct format")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Username required")]
        public string Username { get; set; }

        public string FName { get; set; }
        public string LName { get; set; }
        public string PhoneNumber { get; set; }


        [InverseProperty("MadeBy")]
        public virtual ICollection<Purchase> Purchases { get; private set; }

        [InverseProperty("AppUsers")]
        public virtual ICollection<Household> Households { get; private set; }

        [InverseProperty("MadeBy")]
        public virtual ICollection<Wish> MadeWishes { get; private set; }

        [InverseProperty("GrantedBy")]
        public virtual ICollection<Wish> GrantedWishes { get; private set; }

        
    }
}
