//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwnData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Household
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Household()
        {
            this.Things = new HashSet<Thing>();
            this.AppUsers = new HashSet<AppUser>();
            this.Purchases = new HashSet<Purchase>();
        }
    
        [Key]
        public int HouseholdId { get; set; }

        [Required(ErrorMessage = "A name is required. This can be anything.")]
        public string Name { get; set; }

        public string Address { get; set; }

    
        [InverseProperty("Household")]
        public virtual ICollection<Thing> Things { get; private set; }

        [InverseProperty("Households")]
        public virtual ICollection<AppUser> AppUsers { get; private set; }
        
        [InverseProperty("Household")]
        public virtual ICollection<Purchase> Purchases { get; private set; }
    }
}
