//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwnData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.Design;

    public partial class Purchase
    {
        [Key]
        public int PurchaseId { get; set; }
        public System.DateTime MadeOn { get; set; }
        public double Paid { get; set; }
        public int MadeById { get; set; }
        public int ThingId { get; set; }
        public int HouseholdId { get; set; }


        [ForeignKey("MadeById")]
        public virtual AppUser MadeBy { get; private set; }

        [ForeignKey("HouseholdId")]
        public virtual Household Household { get; private set; }

        [ForeignKey("ThingId")]
        public virtual Thing Thing { get; private set; }
    }
}
