//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwnData
{
    using System;
    
    public enum Status : byte
    {
        Cancelled = 0,
        BoughtNotPaid = 1,
        BoughtPaid = 2,
        Pending = 3
    }
}
