//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwnData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Thing
    {
        public Thing()
        {
            this.DefaultPrice = 0;
            this.Needed = false;
            this.Purchases = new HashSet<Purchase>();
        }
    
        [Key]
        public int ThingId { get; set; }

        [Required(ErrorMessage = "Name required")]
        public string Name { get; set; }

        [Required]
        public int HouseholdId { get; set; }

        public bool Needed { get; set; }

        public double DefaultPrice { get; set; }
    
        [InverseProperty("Thing")]
        public virtual ICollection<Purchase> Purchases { get; set; }

        [ForeignKey("HouseholdId")]
        public virtual Household Household { get; set; }
    }
}
