//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThingsWeNeed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thing
    {
        public int ThingId { get; set; }
        public string Name { get; set; }
        public bool Needed { get; set; }
        public int HouseholdId { get; set; }
    }
}
