//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThingsWeNeed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wish
    {
        public int WIshId { get; set; }
        public double MaxPrice { get; set; }
        public double ExtraPay { get; set; }
        public System.DateTime MadeOn { get; set; }
        public Nullable<System.DateTime> BoughtOn { get; set; }
        public Status Status { get; set; }
        public int MadeByUserId { get; set; }
        public Nullable<int> GrantedByUserId { get; set; }
        public string Name { get; set; }
    
        public virtual AppUser MadeBy { get; private set; }
        public virtual AppUser GrantedBy { get; private set; }
    }
}
