//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseId { get; set; }
        public System.DateTime MadeOn { get; set; }
        public double Paid { get; set; }
        public int AppUser_UserId { get; set; }
        public int Household_HouseholdId { get; set; }
        public int Thing_ThingId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Household Household { get; set; }
        public virtual Thing Thing { get; set; }
    }
}
